- name: Create a Deployment for NGINX
  community.kubernetes.k8s:
    state: absent
    definition:
      api_version: apps/v1
      kind: Deployment
      metadata:
        name: nginx
        namespace: default
      spec:
        selector:
          matchLabels:
            app: nginx
        replicas: 2 
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
            - name: nginx
              image: nginx:stable
              ports:
              - containerPort: 80
                name: web
                protocol: TCP 
              readinesProbe:
                httpGet:
                  port: web
                  path: /


- name: Create NodePort on port 31111 for NGINX
  community.kubernetes.k8s:
    state: absent
    definition:
      api_version: apps/v1
      kind: Service
      metadata:
        name: nginx-nodeport
        namespace: default
      spec:
        type: NodePort
        selector:
          app: nginx
        ports:
          - name: web
            port: 80
            targetPort: web
            nodePort: 31111