---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: master
  become: yes
  environment:
    KUBECONFIG: "~/.kube/config:/etc/rancher/k3s/k3s.yaml"
  roles:
    - role: k3s/master
    - role: k3s/common/docker
    - role: nginx
    - role: pihole

- hosts: node
  become: yes
  roles:
    - role: k3s/node
    - role: k3s/common/docker
